def usage():
    print('\t-c, --config_file <configFile> : Set config file')
    print('\t\tExample : ... -c /home/harkame/config.yml')
    print('\t\tDefault : ./config_file.yml')
    print('\t-d, --destination_path <destinationPath> : Set destination path where download mangas')
    print('\t\tExample : ... -d /home/harkame/mangas')
    print('\t\tDefault : ./mangas')
    print('\t-f, --format <mangaFormat> : Change format of downloaded mangas')
    print('\tsupported format : png, pdf, cbz')
    print('\t\tExample : ... -f pdf')
    print('\t\tDefault : png')
    print('\t-h, --help : Print this help')
    print('\t\tExample : ... -h')
    print('\t-v, --verbose : Activate verbose mod (debug, info, error)')
    print('\t\tExample : ... -v')
